<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXEHJL1A\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXEHJL1A/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXEHJL1A.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXEHJL1A\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXEHJL1A\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XEHJL1A',
    'container.build_id' => '40a1ed01',
    'container.build_time' => 1563897779,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXEHJL1A');
