<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPrLy8u5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPrLy8u5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPrLy8u5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPrLy8u5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPrLy8u5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PrLy8u5',
    'container.build_id' => '346e0e99',
    'container.build_time' => 1563884703,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPrLy8u5');
