<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDVBNtiw\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDVBNtiw/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDVBNtiw.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDVBNtiw\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDVBNtiw\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DVBNtiw',
    'container.build_id' => '80ec168d',
    'container.build_time' => 1563979817,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDVBNtiw');
